### PR TITLE
Info page improvements and wireframe for infos updated

### PR DESCRIPTION
**Pull request by zhorzhz**

### CODE REVIEW

**Review by estshen — APPROVED** [review]
Looking great!

**Review by pmcclure852 — APPROVED** [review]
I'm happy with this too, perhaps consider changing the banner image size to match the home page while you're resolving the conflicts (maybe this is a non-issue!).

**Review by KimberlyO367 — APPROVED** [review]
Looks good!

**Comment by KimberlyO367** [comment]
Overall, it looks good! I was just thinking, this isn't a big deal and no worries if we don't have time to change it. It seems like the class put a lot of importance on text styling to relay meaning. I wonder if the text in the heading boxes should be bigger like the 'warning, details, etc' since they are acting like headings. And for the details box there is a lot of white space, maybe we could add an image there or make the text bigger? Just a thought!

**Pull request merged**
