### PR TITLE
Create Theme Park Wireframes.xd with some html for the header/navigation, created HTML pages

### PR DESCRIPTION
**Pull request by pmcclure852**

### CODE REVIEW

**Review by KimberlyO367 — COMMENTED** [review]
Hey @pmcclure852 , can you add some screenshots of the xd file and the html one here in the peer description so we can see what it looks like, thank you!

**Comment by pmcclure852** [comment]
> Hey @pmcclure852 , can you add some screenshots of the xd file and the html one here in the peer description so we can see what it looks like, thank you!

Hi @KimberlyO367 not sure how to do this on web, I guess you could download the files, but if you're on github desktop, you can switch branch to my branch, and then my updated files will be the ones on your computer, you can then open them in adobe XD or brackets or your web browser etc. and have a look around. Does that make any sense at all!? 

Or is it better/the usual process to just supply screen shots with your pull request?

**Comment by KimberlyO367** [comment]
Yeah! That makes sense I was able to pull them up, to add the screenshot, you can drag the screenshot in this box, dunno if we want to add screenshots so we can see a quick view of how it looks like
Home page

**Comment by pmcclure852** [comment]
Closed for now, will use @KimberlyO367 's files once they're in main.

**Pull request closed without merging**
