### PR TITLE
Changed attractions page background to white; updated the banner imag…

### PR DESCRIPTION
**Pull request by estshen**
…e text to match the home page; changed banner image to fix copyright issue; updated a few comments so that it's easier to read

### CODE REVIEW

**Review by pmcclure852 — CHANGES_REQUESTED** [review]
I would suggest perhaps changing the background colour of the squares around the attractions while not hovering over them to make them clearer, they aren't very clear because the colour is so close to white.

When I'm previewing the page through webstorm, unless I open the developer options I can't see your sub heading. Does it work ok for you?

Also, the header text doesn't quite match the home page,  maybe align lift and add some bold?

image

image

**Comment by estshen** [comment]
> I would suggest perhaps changing the background colour of the squares around the attractions while not hovering over them to make them clearer, they aren't very clear because the colour is so close to white.
> 
> When I'm previewing the page through webstorm, unless I open the developer options I can't see your sub heading. Does it work ok for you?
> 
> Also, the header text doesn't quite match the home page, maybe align lift and add some bold?
> 
> image
> 
> image

Thanks for the suggestion, I'll try to see what colours match well :) The header looks fine for me tho on vscode?
Xnip2021-01-06_22-25-54

**Comment by KimberlyO367** [comment]
The banner is looking different for me too than the one on the home page, the text & sizing. I was looking at your code, I think you could just copy the banner in the home page and then you'd just need to change the image to the attractions image, and remove the old banner css code and make sure the home page banner css is applying, if that makes sense? Maybe we can add a color to the square backgrounds color, instead of white you could use the 4 different colors used on the home page

**Comment by pmcclure852** [comment]
Yeah, it's still not working correctly even when I launch it through vscode. Actually, if I don't launch it through any code editor, just from windows explorer it's not working either. 

Are you using chrome or a different web browser?

**Comment by estshen** [comment]
Yeah I'm using chrome, maybe there's some compatibility issue? The other pages also look a bit different on my laptop, it's a bit late here, but I'll see what I can do tmr :)

https://user-images.githubusercontent.com/61719809/103787902-2fe90f80-5079-11eb-9fc4-5c27d8ef2340.mov

**Comment by pmcclure852** [comment]
Maybe it's your magical mac! I'm slumming it on windows :)

**Comment by KimberlyO367** [comment]
> 
> 
> Yeah I'm using chrome, maybe there's some compatibility issue? The other pages also look a bit different on my laptop, it's a bit late here, but I'll see what I can do tmr :)
> Screen.Recording.2021-01-06.at.11.34.43.PM.mov

Thanks for uploading that video! I didn't realize on the home page banner when the screen size is small it distorts the text, I'll fix that :) As for the attractions page, I think I'm seeing the same as Phil here, here's a video of what it looks like on chrome for me w/windows. Oh and I just noticed! Could you delete line 8, the bootstrap link? I think that was from when we had bootstrap on the home page 


https://user-images.githubusercontent.com/75389506/103791431-5a67a800-503a-11eb-9484-4f5f49adc362.mov

**Comment by pmcclure852** [comment]
I had an idea - when you're happy with what you've done @jenhshen, will you use the website uploader on the course (week 10) and share the link? That way we can see what it will look like when hosted from somewhere independent of our own computers and how the examiners will see it?

**Comment by estshen** [comment]
@KimberlyO367 Yeah, no problem! I just pushed the update. 

@pmcclure852 That’s a good idea! Here’s the link  https://hub.coursera-apps.org/connect/sharedqjkkuwgy 
Does it look ok on your browsers? Mine looks like this

https://user-images.githubusercontent.com/61719809/103879476-e220e580-5112-11eb-9d7d-9d0f4cbfef2e.mov

**Comment by KimberlyO367** [comment]
> 
> 
> @KimberlyO367 Yeah, no problem! I just pushed the update.
> 
> @pmcclure852 That’s a good idea! Here’s the link https://hub.coursera-apps.org/connect/sharedqjkkuwgy
> Does it look ok on your browsers? Mine looks like this
> Screen.Recording.2021-01-07.at.6.00.49.PM.mov

I can see the boxes on my screen now! :) It's just the banner size and text styling isn't matching the home page for me

**Comment by pmcclure852** [comment]
Weird, it's still broken over here...

https://user-images.githubusercontent.com/74780291/103894575-08309080-50e7-11eb-9da6-6ad69dc86b36.mp4

**Comment by KimberlyO367** [comment]
That's so weird! This is what it looks like on firefox for me 
screenshot

**Comment by pmcclure852** [comment]
I've figured it out - the text scales and moves behind the the box when the size of the window is changed. I've got a pretty massive monitor perhaps that's why I'm more aware of the issue?

Excuse the phone recording, windows doesn't like it when you resize the window while recording!


https://user-images.githubusercontent.com/74780291/103897160-049f0880-50eb-11eb-81e5-d91af48a7213.mp4

**Pull request closed without merging**
