### PR TITLE
Adding CSS to header and footer and made a logo

### PR DESCRIPTION
**Pull request by pmcclure852**
Added CSS for header and footer and quickly made a logo with an online tool I found.

Looks a little tacky but not too bad I think!

I very quickly changed the style of the buttons to match a little, if you like the logo design, I could create buttons to match. I think that would look ok.

image

The footer is boring but matches the wireframe. I think we could do with reviewing what it says on the buttons in both the header and footer probably.

image

### CODE REVIEW

**Comment by pmcclure852** [comment]
It seems I forgot to update the comments when I commited/pushed - this has nothing to do with reverting back to Jen's upload :)

**Comment by KimberlyO367** [comment]
I think it looks decent! For the header maybe the buttons should be "home" "rides" "info" "book now" What are your thoughts on what the buttons should say in the footer? I'm not sure! Policy does relate to the covid-policy, we don't have a career section though, hmm

**Review by KimberlyO367 — APPROVED** [review]
Looks good! Might need to change the color a bit though depending what color theme we go with

**Review by estshen — APPROVED** [review]
Looks good to me!

**Comment by pmcclure852** [comment]
I've created an alternative but not pushed...


https://user-images.githubusercontent.com/74780291/103002953-c53bbe00-4527-11eb-8984-f9b557bd61d0.mp4

**Comment by KimberlyO367** [comment]
> 
> 
> I've created an alternative but not pushed...
> Filmopolis.Home.Page.-.Google.Chrome.2020-12-23.14-03-00.mp4

I like this!

**Comment by pmcclure852** [comment]
image

- Made footer match the header
- Changed text on nav items
- Created mailto: email contact in footer
- Used # in url to jump to covid policy

I'm pretty happy with how things are with the header and footer now.

@zhorzhz I'm having problems with the map overlapping the footer, perhaps you could help with that? I think the maps needs some work perhaps anyway?

I had a little look at implementing different colours using https://coolors.co/u/kimberly52 but wasn't really happy with any of the results. Maybe if we get this pull request accepted and merged we could all take a look and see if we can figure something out we like?

**Pull request merged**
