### PR TITLE
Jen update 2

### PR DESCRIPTION
**Pull request by estshen**
Made changes based on @KimberlyO367 's updates, I like your lightsaber so I added some glowing effect! The font family "'Pacifico', cursive" looks like this on my laptop, it's not as the same as the pic in the slack channel I think?

(not sure why the previous one was automatically approved, so posting again)

https://user-images.githubusercontent.com/61719809/103986973-a7788500-51c6-11eb-8e6b-442b59e126cc.mov

### CODE REVIEW

**Comment by pmcclure852** [comment]
Hey @jenhshen it looks like maybe you hit the 'Close with comment' button by accident on your last pull request so it just closed, I think you can re-open them if that happens.

The font doesn't look right because you don't have 'Pacifico' installed on your computer so it's moving along to the next option 'cursive' which is the just telling the browser to use the default cursive font. This is like if you use "'Helvetica', sans-serif", if you don't have helvetica installed, you would get whatever the default sans-serif font your computer chooses.

If you want to use an unusual font or an absolutely specific font like in this case with pacifico, you have to tell the browser to download the font so it will have it available, and we still have the default cursive option fall-back in case that doesn't work for whatever reason. You do this in the the html file in the <head> of the document.

I picked this font from [google fonts](https://fonts.google.com/) which gives you the code to use nice and easy. It's the first time I've done this and it was a pretty good site to use I thought!

You add:

`<link rel="preconnect" href="https://fonts.gstatic.com">` - this code 'preconnects' to the font host to speed up loading the font when the browser finds an occurrence of something from google fonts in the css.

`<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">` - this is the actual font so it knows where to look to download it.

**Comment by estshen** [comment]
Oh I probably forgot to invite reviewers and the request somehow got approved, don’t know why, so I closed it haha.

Thanks for the explanation, this makes so much sense now! Yeah google fonts make the site look more fun! I fixed the issue, but seems like this request is conflicting with main, let me see what I can do!

**Review by KimberlyO367 — APPROVED** [review]
I like how you used the same font. For the glow effect, I was considering using a glow effect too but I was having trouble making it look nice with the banner image used on the index page, and I was thinking maybe it would be hard to read if someone was vision impaired? Idunno! You'll probably have some conflicts to resolve when merging, I had to resolve some when I merged the updated index, it was tricky! Let us know if you need any help :]

**Comment by estshen** [comment]
I like how considerate you are, that’s so sweet! Thank you! Will be extra careful when I work on it!

**Comment by pmcclure852** [comment]
Hey @jenhshen, it's looking good, I just have a couple of suggestions:

I think it would flow better better if the banner image was the same size as on the home page, I made a mock up in a photo editing app. It's not a big deal if you've not got time though, just a suggestion.

image

More importantly, I also think the glow might be an issue, perhaps you could add the same shadow effect as on the home page instead?
I think these are the settings:

.banner-welcome {
    position: absolute;
    left: 100px;
    top: 20px;
    color: white;
    font-family: Arial, Helvetica, sans-serif;
    line-height: 1;
    text-shadow: 0 0 6px #000000a8;
    font-size: 2.4vw;
}

.banner-brand {
    font-size: 7.4em !important;
    text-shadow: 0 0 16px #00000057;
    font-family: Pacifico, cursive, Arial, Helvetica, sans-serif;
    font-weight: lighter;
    color: rgba(0, 0, 0, .31);
}

**Review by zhorzhz — APPROVED** [review]

**Comment by estshen** [comment]
Thanks for the advice and making the mock up, I really appreciate it! :) I've tweaked the banner width and added the shadow effect, does it look better? Let me know what you think! I saw Zhorzhz pulled a new request, I'm going to merge this one first, but I'm happy to make updates if you have other ideas!
Xnip2021-01-09_09-10-42

**Pull request merged**
